"use client";

import { AnimatePresence, motion } from "framer-motion";
import { usePathname, useSearchParams } from "next/navigation";
import { useMemo, useState } from "react";
import type { CandidateProfileDebug, PlaylistCandidate } from "@/lib/types";
import { VIBE_DIRECTION_LABELS } from "@/lib/vibeProfile";
import {
  PressableCard,
  PressableChip,
  SlideUp,
  StaggerGroup,
  StaggerItem,
  useMotionConfig,
} from "@/components/motion";
import { useSpotifySession } from "./SpotifyConnectButton";

const SOURCE_LABELS: Record<string, string> = {
  lastfm_similar_artist: "Last.fm similar artist",
  lastfm_tag_seed: "Last.fm tag seed",
  spotify_search: "Spotify search",
  musicbrainz_related_recording: "MusicBrainz related",
  musicbrainz_credit: "MusicBrainz credit",
  curated_fallback: "Curated fallback",
};

const DIRECTION_LABELS = VIBE_DIRECTION_LABELS;

type PlaylistCandidatesProps = {
  playlists: PlaylistCandidate[];
  seedTrackUri: string;
  showVibeDebug?: boolean;
};

function CandidateDebugPanel({ debug }: { debug: CandidateProfileDebug }) {
  return (
    <details className="mt-2 rounded-lg border border-amber-500/20 bg-amber-500/5 px-3 py-2 text-[10px]">
      <summary className="cursor-pointer font-medium uppercase tracking-wider text-amber-200/90">
        Taste / vibe debug
      </summary>
      <div className="mt-2 space-y-2 font-mono text-amber-100/80">
        {debug.tasteCloseness !== undefined && (
          <p>taste closeness: {Math.round(debug.tasteCloseness * 100)}%</p>
        )}
        {debug.vibeCloseness !== undefined && (
          <p>vibe closeness: {Math.round(debug.vibeCloseness * 100)}%</p>
        )}
        {debug.taste && (
          <pre className="overflow-x-auto whitespace-pre-wrap break-words">
            taste: {JSON.stringify(debug.taste, null, 2)}
          </pre>
        )}
        {debug.vibe && (
          <pre className="overflow-x-auto whitespace-pre-wrap break-words">
            vibe: {JSON.stringify(debug.vibe, null, 2)}
          </pre>
        )}
      </div>
    </details>
  );
}

type SaveState =
  | { status: "idle" }
  | { status: "saving"; step: string }
  | { status: "success"; playlistUrl: string; added: number; skipped: number }
  | { status: "error"; message: string };

function SavePlaylistButton({
  playlist,
  seedTrackUri,
  returnTo,
}: {
  playlist: PlaylistCandidate;
  seedTrackUri: string;
  returnTo: string;
}) {
  const { loggedIn } = useSpotifySession();
  const [selected, setSelected] = useState<boolean[]>(
    playlist.tracks.map(() => true),
  );
  const [saveState, setSaveState] = useState<SaveState>({ status: "idle" });

  const selectedTracks = useMemo(
    () => playlist.tracks.filter((_, index) => selected[index]),
    [playlist.tracks, selected],
  );

  function toggleTrack(index: number) {
    setSelected((current) =>
      current.map((value, i) => (i === index ? !value : value)),
    );
  }

  async function handleSave() {
    if (selectedTracks.length === 0) {
      setSaveState({
        status: "error",
        message: "Select at least one track to save.",
      });
      return;
    }

    setSaveState({ status: "saving", step: "Resolving tracks on Spotify…" });

    try {
      const resolveResponse = await fetch("/api/spotify/search-tracks", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          tracks: selectedTracks.map((track) => ({
            title: track.title,
            artist: track.artist,
            uri: track.spotifyUri ?? (track.isSeed ? seedTrackUri : undefined),
          })),
        }),
      });

      const resolveData = (await resolveResponse.json()) as {
        uris?: string[];
        matchedCount?: number;
        totalCount?: number;
        error?: string;
      };

      if (!resolveResponse.ok) {
        throw new Error(resolveData.error ?? "Failed to resolve tracks.");
      }

      const uris = resolveData.uris ?? [];
      if (uris.length === 0) {
        throw new Error("No selected tracks could be matched on Spotify.");
      }

      setSaveState({ status: "saving", step: "Creating private playlist…" });

      const createResponse = await fetch("/api/spotify/playlists", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: `Music Story — ${playlist.name}`,
          description: `${playlist.description} (Generated by Music Story MVP)`,
          public: false,
        }),
      });

      const createData = (await createResponse.json()) as {
        playlist?: { id: string; url: string };
        error?: string;
      };

      if (!createResponse.ok || !createData.playlist) {
        throw new Error(createData.error ?? "Failed to create playlist.");
      }

      setSaveState({ status: "saving", step: "Adding tracks…" });

      const addResponse = await fetch(
        `/api/spotify/playlists/${createData.playlist.id}/tracks`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ uris }),
        },
      );

      const addData = (await addResponse.json()) as { error?: string };

      if (!addResponse.ok) {
        throw new Error(addData.error ?? "Failed to add tracks.");
      }

      setSaveState({
        status: "success",
        playlistUrl: createData.playlist.url,
        added: uris.length,
        skipped: selectedTracks.length - uris.length,
      });
    } catch (error) {
      setSaveState({
        status: "error",
        message:
          error instanceof Error ? error.message : "Could not save playlist.",
      });
    }
  }

  if (loggedIn === null) {
    return (
      <button
        type="button"
        disabled
        className="mt-5 w-full rounded-2xl border border-border bg-surface-elevated px-4 py-3 text-sm font-medium text-muted"
      >
        Checking Spotify session…
      </button>
    );
  }

  if (!loggedIn) {
    return (
      <a
        href={`/api/auth/spotify?returnTo=${encodeURIComponent(returnTo)}`}
        className="mt-5 flex w-full items-center justify-center rounded-2xl border border-accent/30 bg-accent/10 px-4 py-3 text-sm font-medium text-accent transition-colors hover:bg-accent/15"
      >
        Connect Spotify to save this playlist
      </a>
    );
  }

  return (
    <div className="mt-5 space-y-3">
      <div className="rounded-2xl border border-dashed border-border/80 bg-surface/40 px-4 py-3 text-xs leading-relaxed text-muted">
        MVP auth stores tokens in a local httpOnly cookie on this device only.
        Playlist will be created as private.
      </div>

      <div className="space-y-2">
        {playlist.tracks.map((track, index) => (
          <label
            key={`${playlist.id}-select-${index}`}
            className="flex cursor-pointer items-start gap-3 rounded-xl border border-border/60 bg-surface-elevated/30 px-3 py-2.5"
          >
            <input
              type="checkbox"
              checked={selected[index]}
              onChange={() => toggleTrack(index)}
              className="mt-1"
            />
            <span className="min-w-0 text-sm">
              <span className="font-medium">{track.title}</span>
              <span className="text-muted"> · {track.artist}</span>
            </span>
          </label>
        ))}
      </div>

      {saveState.status === "error" && (
        <p className="text-sm text-red-400/90" role="alert">
          {saveState.message}
        </p>
      )}

      {saveState.status === "success" && (
        <AnimatePresence mode="wait">
          <motion.div
            key="success"
            initial={{ opacity: 0, scale: 0.96, y: 8 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.98 }}
            transition={{ type: "spring", stiffness: 380, damping: 28 }}
            className="rounded-2xl border border-emerald-500/30 bg-emerald-500/10 px-4 py-3 text-sm shadow-[0_0_24px_-8px_rgba(52,211,153,0.35)]"
          >
            <p className="font-medium text-foreground">
              Private playlist created — {saveState.added} track
              {saveState.added === 1 ? "" : "s"} added
              {saveState.skipped > 0
                ? ` (${saveState.skipped} could not be matched)`
                : ""}
              .
            </p>
            <a
              href={saveState.playlistUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="mt-2 inline-block text-accent underline-offset-2 hover:underline"
            >
              Open in Spotify
            </a>
          </motion.div>
        </AnimatePresence>
      )}

      <button
        type="button"
        onClick={() => void handleSave()}
        disabled={saveState.status === "saving" || selectedTracks.length === 0}
        className="w-full rounded-2xl border border-accent/30 bg-accent px-4 py-3 text-sm font-medium text-background transition-colors hover:bg-accent/90 disabled:cursor-not-allowed disabled:opacity-60"
      >
        {saveState.status === "saving"
          ? saveState.step
          : `Create private playlist (${selectedTracks.length} selected)`}
      </button>
    </div>
  );
}

export function PlaylistCandidates({
  playlists,
  seedTrackUri,
  showVibeDebug = false,
}: PlaylistCandidatesProps) {
  const pathname = usePathname();
  const searchParams = useSearchParams();
  const { reduced } = useMotionConfig();
  const returnTo = useMemo(() => {
    const query = searchParams.toString();
    return query ? `${pathname}?${query}` : pathname;
  }, [pathname, searchParams]);

  if (playlists.length === 0) return null;

  return (
    <section className="relative pt-4">
      <div
        className="pointer-events-none absolute -top-8 left-1/2 h-px w-24 -translate-x-1/2 bg-gradient-to-r from-transparent via-accent/40 to-transparent"
        aria-hidden
      />

      <SlideUp className="mb-8 text-center">
        <p className="text-xs font-medium uppercase tracking-[0.25em] text-accent">
          Where to next
        </p>
        <h2 className="mt-2 font-display text-2xl font-medium">
          Recommended playlists
        </h2>
        <p className="mx-auto mt-2 max-w-xs text-sm leading-relaxed text-muted">
          Select tracks, connect Spotify, and save a private playlist.
        </p>
      </SlideUp>

      <ul className="space-y-5">
        {playlists.map((playlist, index) => (
          <li
            key={playlist.id}
            style={{ marginLeft: index % 2 === 1 ? "1rem" : "0" }}
          >
            <SlideUp delay={0.12 + index * 0.1}>
              <PressableCard className="rounded-3xl border border-border bg-surface p-6">
              <div className="flex items-start justify-between gap-4">
                <div>
                  <span className="text-[10px] font-medium uppercase tracking-[0.18em] text-muted">
                    Path {index + 1}
                  </span>
                  <h3 className="mt-1 font-display text-xl font-medium">
                    {playlist.name}
                  </h3>
                  <p className="mt-1.5 text-sm text-muted">
                    {playlist.description}
                  </p>
                </div>
                <span className="shrink-0 rounded-full border border-border bg-surface-elevated px-2.5 py-1 text-[11px] text-muted">
                  {playlist.trackCount}
                </span>
              </div>

              <p className="mt-4 text-[11px] font-medium uppercase tracking-wider text-accent/80">
                {playlist.vibe}
              </p>

              {playlist.availableDirections &&
                playlist.availableDirections.length > 0 && (
                  <div className="mt-3 flex flex-wrap gap-2">
                    {playlist.availableDirections.map((direction) => (
                      <PressableChip
                        key={`${playlist.id}-${direction}`}
                        className="cursor-default rounded-full border border-border/70 bg-surface-elevated/50 px-2.5 py-1 text-[10px] font-medium uppercase tracking-wider text-muted"
                        title="Direction filtering coming soon"
                      >
                        {DIRECTION_LABELS[direction] ?? direction}
                      </PressableChip>
                    ))}
                  </div>
                )}

              <StaggerGroup
                className="mt-4 space-y-4 border-t border-border pt-4"
                delayChildren={0.08}
              >
                {playlist.tracks.map((track, i) => (
                  <StaggerItem key={`${playlist.id}-${i}`}>
                    <div className="rounded-2xl border border-border/60 bg-surface-elevated/40 px-4 py-3">
                    <div className="flex items-start justify-between gap-3">
                      <div className="min-w-0">
                        <p
                          className={`text-sm font-medium ${track.isSeed ? "text-foreground" : "text-foreground/90"}`}
                        >
                          {track.title}
                        </p>
                        <p className="mt-0.5 text-sm text-muted">{track.artist}</p>
                      </div>
                      <div className="shrink-0 text-right">
                        {track.isSeed && (
                          <span className="mb-1 block text-[10px] uppercase tracking-wider text-accent">
                            Seed
                          </span>
                        )}
                        <span className="text-[11px] tabular-nums text-muted">
                          {Math.round(track.confidence * 100)}%
                        </span>
                      </div>
                    </div>
                    <motion.p
                      className="mt-2 text-xs leading-relaxed text-muted"
                      initial={reduced ? false : { opacity: 0 }}
                      animate={{ opacity: 1 }}
                      transition={{ delay: 0.15 + i * 0.05, duration: 0.4 }}
                    >
                      {track.reason}
                    </motion.p>
                    {track.vibeProfile?.label && (
                      <motion.p
                        className="mt-1.5 text-[11px] text-foreground/70"
                        initial={reduced ? false : { opacity: 0 }}
                        animate={{ opacity: 1 }}
                        transition={{ delay: 0.2 + i * 0.05, duration: 0.35 }}
                      >
                        Vibe: {track.vibeProfile.label}
                      </motion.p>
                    )}
                    {track.tasteProfile?.label && (
                      <motion.p
                        className="mt-1 text-[11px] text-muted/80"
                        initial={reduced ? false : { opacity: 0 }}
                        animate={{ opacity: 1 }}
                        transition={{ delay: 0.22 + i * 0.05, duration: 0.35 }}
                      >
                        Taste: {track.tasteProfile.label}
                      </motion.p>
                    )}
                    {track.vibeDirectionHints &&
                      track.vibeDirectionHints.length > 0 && (
                        <div className="mt-2 flex flex-wrap gap-1.5">
                          {track.vibeDirectionHints.map((hint) => (
                            <PressableChip
                              key={`${playlist.id}-${i}-${hint}`}
                              className="rounded-md border border-accent/15 bg-accent/5 px-1.5 py-0.5 text-[9px] uppercase tracking-wider text-accent/80"
                            >
                              {DIRECTION_LABELS[hint] ?? hint}
                            </PressableChip>
                          ))}
                        </div>
                      )}
                    {showVibeDebug && track.debug && (
                      <CandidateDebugPanel debug={track.debug} />
                    )}
                    <motion.p
                      className="mt-1.5 text-[10px] uppercase tracking-wider text-muted/70"
                      initial={reduced ? false : { opacity: 0 }}
                      animate={{ opacity: 1 }}
                      transition={{ delay: 0.28 + i * 0.05, duration: 0.35 }}
                    >
                      {SOURCE_LABELS[track.source] ?? track.source}
                    </motion.p>
                    </div>
                  </StaggerItem>
                ))}
              </StaggerGroup>

              <SavePlaylistButton
                playlist={playlist}
                seedTrackUri={seedTrackUri}
                returnTo={returnTo}
              />
              </PressableCard>
            </SlideUp>
          </li>
        ))}
      </ul>
    </section>
  );
}
